In LV-Zyklus Systemtechnik werden verschiedene Arten von Systemen
behandelt. Deshalb soll zunächst eine Klärung des Begriffs /System/
versucht werden.

* Systembegriff
  :PROPERTIES:
  :CUSTOM_ID: systembegriff
  :END:

Problemlösung mit Hilfe von Rechnern:

-  einfache Probleme $\to$ einfache, überschaubare Programme

-  komplexe Probleme\\
   $\to$ Erarbeitung von Teillösungen, es entstehen Komponenten einer
   Gesamtlösung, die zusammenarbeiten müssen.\\
   $\Rightarrow$ System

-  in DV-Systemen typisch:\\
   parallel ablaufende Aktivitäten auf verschiedenen technischen
   Komponenten (Betriebsmittel)

* Informationsverarbeitende Systeme
  :PROPERTIES:
  :CUSTOM_ID: informationsverarbeitende-systeme
  :END:

Informationsverarbeitende Systeme bestehen - hardware-technisch -
gesehen aus einer Vielzahl von aktiven und passiven Komponenten:

-  /aktiv:/ Prozessoren, Peripheriegeräte

-  /passiv:/ Speicher

Abbildung [Beschreibungsebenen] zeigt die Beschreibungsebenen eines
informationsverarbeitenden Systems.

#+CAPTION: [Beschreibungsebenen] Beschreibungsebenen eines
informationsverarbeitenden Systems
[[file:bild-1.eps]]

Das Betriebssystem stellt die fundamentalste Komponente der
Systemsoftware dar. Aufgaben, Strukturen und Prinzipien von
Betriebssystemen finden sich in ähnlicher Form auch in anderen
informationsverarbeitenden Systemen wieder (z.B. Datenbanksysteme,
Flugbuchung, Produktionsüberwachung und -steuerung).

Architekturen von Betriebssystemen werden im folgenden stellvertretend
für andere Systemarchitekturen betrachtet.

**** Erste grundlegende Aufgabe eines Betriebssystems:
     :PROPERTIES:
     :CUSTOM_ID: erste-grundlegende-aufgabe-eines-betriebssystems
     :END:

Bereitstellen einer virtuellen (abstrakten) Maschine, d.h. Befreiung des
Programmierers von Hardwaredetails.\\

***** Beispiel:
      :PROPERTIES:
      :CUSTOM_ID: beispiel
      :END:

Lesen eines Datenblocks von einer Festplatte\\
Vorteile:

-  Drucken mit endlosem Papiervorrat

-  fehlerfreie Datenübertragung

Nachteile:

-  u.U. nur unzureichende Unterstützung der Leistungsfähigkeit
   spezieller Geräte (Beispiel: hochauflösender Grafikbildschirm wird
   zum Fernschreiber "degradiert")

-  "primitives" Dateikonzept (vgl. z.B. PASCAL)

**** Definition nach DIN 44300
     :PROPERTIES:
     :CUSTOM_ID: definition-nach-din-44300
     :CLASS: unnumbered
     :END:

"Betriebssystem (/operating system/): Die Programme eines digitalen
Rechensystems, die zusammen mit den Eigenschaften der Rechenanlage die
Basis der möglichen Betriebsarten des ditigalen Rechensystems bilden und
insbesondere die Abwicklung von Programmen steuern und überwachen.\\
Eine Sprache, der ein Betriebssystem gehorcht, heißt Betriebssprache
(/operating language/)."

**** Zweite grundlegende Aufgabe eines Betriebssystems:
     :PROPERTIES:
     :CUSTOM_ID: zweite-grundlegende-aufgabe-eines-betriebssystems
     :END:

Verwaltung der Betriebsmittel einer Rechenanlage\\
/Beispiele:/ Druckerverwaltung, Speicherverwaltung

* Betriebssystemkategorien und Historie
  :PROPERTIES:
  :CUSTOM_ID: betriebssystemkategorien-und-historie
  :END:

**** Rechner der ersten Generation
     :PROPERTIES:
     :CUSTOM_ID: rechner-der-ersten-generation
     :END:

(Röhren, 1945-1955)\\
Rechner der ersten Generation kannten keine Betriebssysteme. Die
Programmierung erfolgte durch Stecktafeln, später mit Lochkarten.

**** Rechner der zweiten Generation
     :PROPERTIES:
     :CUSTOM_ID: rechner-der-zweiten-generation
     :END:

(Transistoren)\\
Programm- und Dateneingabe erfolgte mit Lochkarten, Ausgabe auf Drucker.
Es gab zwei Betriebsarten:

-  /online/-Betrieb

-  /offline/-Betrieb (Puffern von Ein- und Ausgabe über Magnetbänder)
   sog. /Batch/-Systeme

Abbildung [Batch-System] zeigt das Beispiel eines "frühen"
Batch-Systems.

#+CAPTION: [Batch-System] Batch-System, Bild entnommen aus
\cite{tanenbaum}
[[file:bild-2.eps]]

Die Ausführung eines sogenannten /Batch-Jobs/ umfaßte dabei die
folgenden Schritte:

-  (a) :: Programmierer liefert die Karten ab

-  (b) :: Vorrechner (IBM 1401) liest mehrere Benutzeraufträge (Jobs)
   ein und schreibt sie auf ein Magnetband

-  (c) :: Operator legt Band in Station des Hauptrechners (IBM 7094)
   ein.

-  (d) :: Hauptrechner führt Benutzeraufträge aus und schreibt deren
   Ausgabe auf ein weiteres Magnetband

-  (e, f) :: Ausgabeband wird zum Vorrechner transportiert und
   Ergebnisse werden dort ausgegeben.

Abbildung [Batch-Job] zeigt ein Beispiel eines typischen Batch-Jobs.

#+CAPTION: [Batch-Job] Batch-Job als Kartenstapel, Bild entnommen aus
\cite{tanenbaum}
[[file:bild-3.eps]]

**** Einbenutzersystem im Einprogrammbetrieb
     :PROPERTIES:
     :CUSTOM_ID: einbenutzersystem-im-einprogrammbetrieb
     :END:

 \\
Es gab drei Phasen der Job-Ausführung:

-  Programmeingabe

-  Programmausführung

-  Ergebnisausgabe

Für die folgenden Betrachtungen sollen für die Berechnung von
/Prozessorauslastung/ und /Durchsatz/ diese Formeln benutzt werden:
$$\begin{aligned}
    \mbox{Prozessorauslastung} & = & \frac{\mbox{Ausführungszeit}}{\mbox{Verweildauer des Jobs in der Anlage}} \\
    \mbox{Durchsatz} & = & \frac{\mbox{Anzahl Jobs}}{\mbox{Zeiteinheit}}\end{aligned}$$
Beide Kenngrößen sind bei Terminal-Betrieb (wie z.B. durch einen
Benutzer vor einer Workstation) beliebig schlecht, u.U. aber auch nicht
von großer Bedeutung. Bei einem Betrieb mit Kartenleser und Drucker kann
insbesondere die Eingabezeit drastisch vermindert werden.

***** Zahlenbeispiel:
      :PROPERTIES:
      :CUSTOM_ID: zahlenbeispiel
      :END:

| Eingabezeit (300 Karten):   | 0,3 min.   |
| Ausgabezeit (500 Zeilen):   | 0,5 min.   |
| Berechnungszeit:            | 1 min.     |

Ausgehend von diesem Zahlenbeispiel zeigt die Tabelle in Abbildung
[Auslastung] in der linken Spalte mögliche Zeitangaben für die
Durchführung des Benutzerauftrages im Online-Betrieb, d.h. die
Rechenanlage steht dem Anwender für die Durchführung seines Jobs
exklusiv zur Verfügung.

Betriebssysteme vor 1955 bestanden nur aus einen Einlese- und einem
Druckprogramm. Eine weitergehende Bedienerunterstützung gab es nicht.
Heute kann man sich solche Betreibssysteme nur leisten, wenn Auslastung
und Durchsatz keine Rolle spielen (Personal Computer). Diesen Fall
wollen wir vorerst nicht weiter betrachten.

Um eine Verbesserung von Durchsatz und Auslastung der damals teuren
Hardware zu erzielen, entzog man den Rechner dem direkten Zugriff durch
den Benutzer (closed-shop-Betrieb, offline). Dadurch konnte die
Verweildauer eines Auftrags in der Anlage nahezu auf die Summe von
Eingabezeit, Ausgabezeit und Berechnungszeit reduziert werden. Damit
ergeben sich die in der rechten Spalte in Abbildung [Auslastung]
angegebenen Werte.

l|l /online/-Betrieb & /offline/-Betrieb\\
\\
$\begin{array}{lcl}
        \mbox{Gesamtzeit} & = & 15 \mbox{ min.} \\
        \mbox{Prozessorauslastung} & = & \frac{1}{15} \approx 7\% \\
        \mbox{Durchsatz} & \approx & 4 \frac{\mbox{\small Jobs}}{h}
    \end{array}$ & $\begin{array}{lcl}
        \mbox{Gesamtzeit} & = & 1.8 \mbox{ min.} \\
        \mbox{Prozessorauslastung} & = & \frac{1}{1.8} \approx 55\% \\
        \mbox{Durchsatz} & \approx & 33 \frac{\mbox{\small Jobs}}{h}
    \end{array}$

Voraussetzung für diesen Betrieb war, das die Ablaufsteuerung durch ein
Betriebssystem vorgenommen wurde, daß sich ständig im Hauptspeicher
befinden mußte. Damit entstanden gleichzeitig neue Probleme:

-  Das Betriebssystem mußte gegen "Angriffe" durch die Benutzerprogramme
   geschützt werden.

-  Die Benutzerprogramme müssen nach Ablauf die Kontrolle an das
   Betriebssystem zurückgeben.

**** Rechner der dritten Generation
     :PROPERTIES:
     :CUSTOM_ID: rechner-der-dritten-generation
     :END:

(1965-1980)\\
waren u.a. gekennzeichnet durch:

-  die Verwendung von Integrierte Schaltkreise (ICs, Chips)

-  die Benutzung sowohl für technisch-wissenschaftliche
   (rechenintensive) und kommerzielle (E/A-intensive) Aufgaben

Typische Verteterin war die IBM 360 und ihre Nachfolger (370, 4300,
3080, 3090). Das wichtigste zu lösende Problem war die Verbesserung der
Prozessorauslastung. Abbildung [Beschaftigunglucken] zeigt exemplarisch
die Zeitaufteilung zwischen dem Zentralprozessor und angeschlossenen
Peripheriegeräten, die für die Abwicklung eines Programms benötigt
werden.

(20,8) (0,6)CPU (0,4)Gerät 1 (0,2)Gerät 2 (0,0)Gerät 3 (2,6)(1,0)2
(4,6)(0,-1)2 (4,4)(1,0)2 (6,6)(0,-1)2 (6,6)(1,0)2 (8,6)(0,-1)4
(8,2)(1,0)2 (10,6)(0,-1)4 (10,6)(1,0)2 (12,6)(0,-1)6 (12,0)(1,0)2
(14,6)(0,-1)6 (14,6)(1,0)2

Die deutlich erkennbaren "Beschäftigunglücken" der CPU gaben Anlaß zu
der grundlegenden Idee, diese Beschäftigunglücken für die ineinander
verzahnte Bearbeitung mehrerer Aufträge zu nutzen, wie es in Abbilung
[Mehrprogrammbetrieb] dargestellt ist.

(20,8) (0,6)CPU (0,4)Gerät 1 (0,2)Gerät 2 (0,0)Gerät 3 (2,6)(1,0)2
(4,6)(0,-1)2 (4,4)(1,0)2 (6,6)(0,-1)2 (6,6)(1,0)2 (8,6)(0,-1)4
(8,2)(1,0)2 (10,6)(0,-1)4 (10,6)(1,0)2 (12,6)(0,-1)6 (12,0)(1,0)2
(14,6)(0,-1)6 (14,6)(1,0)2 (4,6)(1,0)1 (5,6)(0,-1)6 (5,0)(1,0)3.5
(8.5,6)(0,-1)6 (8.5,6)(1,0)1 (9.5,6)(0,-1)2 (9.5,4)(1,0)3
(12.5,6)(0,-1)2 (12.5,6)(1,0)1 (13.5,6)(0,-1)4 (13.5,2)(1,0)2.5

**** Mehrprogrammbetrieb
     :PROPERTIES:
     :CUSTOM_ID: mehrprogrammbetrieb
     :END:

 \\
Beim /Mehrprogrammbetrieb/ (/Multiprogramming/) werden die Zeiten,
während der die CPU auf die Fertigstellung einer E/A-Anforderung warten
müßte, für die Bearbeitung eines anderen Benutzerauftrages genutzt. Dies
ist nur unter der Vorraussetzung möglich, daß sich mehrere Programme
(Benutzeraufträge) gleichzeitig im Hauptspeicher befinden. Abbildung
[Hauptspeicher] zeigt eine mögliche Aufteilung des Hauptspeichers.

(10,12) (4,10)(8,1)[l] Gerätesteuerung (4,8)(8,2)[l] Betriebssystem
(4,7)(8,1)[l] Interrupt-Routine (4,5)(8,2)[l] Benutzerauftrag 1
(4,3)(8,2)[l] Benutzerauftrag 2 (4,1)(8,2)[l] Benutzerauftrag 3

Beschränkung der Parallelarbeit ist im wesentlichen gegeben durch:

-  verfügbare Rechenzeit

-  Platz im Hauptspeicher

Das Betriebssystem muß entscheiden können, zu welchen Zeitpunkten
welcher Benutzerauftrag bearbeitet wird. Unterbrechungen (/Interrupt/)
des Zentralprozessors müssen ermöglicht werden. Bei jeder Unterbrechung
muß ein Prozessorverwaltungsprogramm aufgerufen werden. "Langläufer"
müssen unterbrochen werden können (Zeitgeber).

**** Ziel:
     :PROPERTIES:
     :CUSTOM_ID: ziel
     :END:

gerechte Verteilung der verfügbaren Prozessorzeit auf alle
Benutzeraufträge\\
Unter /Prozessen/ sollen vorerst "Träger parallel ablaufender
Aktivitäten" verstanden werden, die die CPU benötigen und selbst jeweils
sequentiell ablaufen.

Aufgaben (und Probleme) des Betriebssystems:

1. /Scheduling/ (Prozessorverwaltung)

2. gerechte Bedienung von Geräteanforderungen

3. /Overhead/: Betriebssystem nimmt den Benutzeraufträgen Rechenzeit
   weg, diese benötigen daher mehr Zeit (Verweildauer im System)

4. Schutz der Prozesse vor gegenseitigen Fehlfunktionen (seperater
   Adreßraum)

5. Zugriffsrechte auf gemeinsam benutzte Daten verwalten

6. Buchführung des Ressourcenverbrauchs

7. "/Spooling/" (über Platten) der Job-Ein- und -Ausgabe

Mehrprogrammbetriebssysteme mit Verdrängung beziehen auch
Benutzeraufträge, die sich z. Zt. nicht im Hauptspeicher befinden, in
die Vergabeplanung von Betriebsmitteln ein. Dies führt zur Ein- und
Auslagerung von Prozessen.

***** Interaktive Mehrbenutzersysteme im Mehrprogrammbetrieb:
      :PROPERTIES:
      :CUSTOM_ID: interaktive-mehrbenutzersysteme-im-mehrprogrammbetrieb
      :END:

/Time-Sharing/-Be"-triebs"-sys"-teme sind eine Weiterentwicklung des
Mehrprogrammbetiebs, bei dem viele Benutzer über Terminals online mit
der Rechenanlage verbunden sind. Als zusätzliche Aufgabe für das
Betriebssystem entsteht die Forderung, jedem Benutzer durch geeignete
Prozessorzuteilung den Eindruck zu vermitteln, die Rechenanlage würde
nur für ihn arbeiten.

**** Rechner der vierten Generation
     :PROPERTIES:
     :CUSTOM_ID: rechner-der-vierten-generation
     :END:

(1980 - heute)\\
*Schlagworte:*

-  Hardware

   -  Höchstintegration (VLSI)

   -  Personal Computer

   -  Workstations

-  Typische Betriebssysteme

   -  MS-DOS (PC)

   -  UNIX

   -  MVS (IBM), VMS (digital)

-  Neuere Entwicklungen

   -  Netzwerk-Betriebssysteme

   -  verteilte Betriebssysteme

* Zusammenfassung
  :PROPERTIES:
  :CUSTOM_ID: zusammenfassung
  :END:

-  Betriebssysteme stellen virtuelle Maschinen mit virtuellen Befehlen
   (genannt Systemaufrufe, /system calls/) bereit. Sie erlauben
   Benutzerprogrammen, Dienstleistungen des Betriebssystems in Anspruch
   zu nehmen.

-  Prozesse (Träger parallel ablaufender Aktivitäten) enthalten ein
   Benutzer- oder Systemprogramm sowie alle für die Ausführung
   notwendigen Informationen (u.a. Befehlszählerstand, Registerinhalte,
   Adreßraum (Speicherabbild, /core-image/)).

   -  Prozeßverwaltung: Erzeugen, Beenden, Suspendieren von Prozessen

   -  Betriebsmittelverwaltung: Hauptspeicherverwaltung,
      Prozessorverwaltung

-  Dateisystem: Verwaltung von Daten mit peripheren Speichermedien

-  Benutzerverwaltung


